# Generated by Django 4.2.1 on 2023-05-31 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('dogID', models.AutoField(primary_key=True, serialize=False)),
                ('chipNum', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('dogName', models.CharField(blank=True, max_length=35, null=True)),
                ('dateOfBirthEst', models.DateField(blank=True, null=True)),
                ('dateOfArrival', models.DateField(blank=True, null=True)),
                ('dateOfVaccination', models.DateField(blank=True, null=True)),
                ('breed', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('furColor', models.CharField(blank=True, max_length=20, null=True)),
                ('isNeutered', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('isDangerous', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('dogImageURL', models.URLField(blank=True, max_length=100, null=True)),
                ('kongDateAdded', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('ownerSerialNum', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('ownerID', models.CharField(blank=True, max_length=9, null=True)),
                ('ownerAddress', models.CharField(blank=True, max_length=70, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneNum', models.CharField(blank=True, max_length=9, null=True)),
                ('cellphoneNum', models.CharField(blank=True, max_length=10, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.CheckConstraint(check=models.Q(('phoneNum__regex', '^[0-9]{9}$')), name='phoneNum_check'),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.CheckConstraint(check=models.Q(('cellphoneNum__regex', '^[0-9]{10}$')), name='cellphoneNum_check'),
        ),
        migrations.AddField(
            model_name='dog',
            name='ownerSerialNum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs_app.owner'),
        ),
    ]
