# Generated by Django 4.2.1 on 2023-06-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Observes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('camID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs_app.camera')),
                ('dogID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs_app.dog')),
            ],
            options={
                'unique_together': {('dogID', 'camID')},
            },
        ),
    ]
