# Generated by Django 4.2.1 on 2023-06-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0002_camera_observes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observes',
            options={'verbose_name_plural': 'Observes'},
        ),
    ]
