# Generated by Django 4.2.1 on 2023-06-01 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0004_treatment_entranceexamination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('kennelNum', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('kennelImageURL', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['kennelNum'],
            },
        ),
        migrations.CreateModel(
            name='DogPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entranceDate', models.DateField(auto_now_add=True)),
                ('expirationDate', models.DateField(blank=True, null=True)),
                ('placementReason', models.CharField(blank=True, max_length=75, null=True)),
                ('dogID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogs_app.dog')),
                ('kennelNum', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogs_app.kennel')),
            ],
            options={
                'ordering': ['-entranceDate'],
                'unique_together': {('dogID', 'kennelNum', 'entranceDate')},
            },
        ),
    ]
