# Generated by Django 4.2.1 on 2023-06-01 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0005_kennel_dogplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogplacement',
            name='entranceDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='examinationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
