# Generated by Django 4.2.1 on 2023-06-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0006_alter_dogplacement_entrancedate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['camID']},
        ),
    ]
