# Generated by Django 4.2.1 on 2023-06-01 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0007_alter_camera_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dogImageURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('sessionDurationsInMins', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('isKong', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('jsonFileURL', models.URLField(blank=True, null=True)),
                ('rawVideoURL', models.URLField(blank=True, null=True)),
                ('camID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogs_app.camera')),
                ('dogID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogs_app.dog')),
            ],
            options={
                'ordering': ['-obsDateTime'],
                'unique_together': {('dogID', 'camID', 'obsDateTime')},
            },
        ),
        migrations.CreateModel(
            name='DogStance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stanceStartTime', models.TimeField()),
                ('dogStance', models.CharField(choices=[('STANDING', 'Standing'), ('SITTING', 'Sitting'), ('WALKING_AROUND', 'Walking Around'), ('SLEEPING_LYING', 'Sleeping/Lying'), ('EATING', 'Eating'), ('DRINKING', 'Drinking'), ('UNDER', 'Under'), ('JUMPING', 'Jumping'), ('PACING', 'Pacing'), ('CIRCLING', 'Circling'), ('ALERT', 'Alert'), ('ELSE', 'Else')], max_length=15)),
                ('dogLocation', models.CharField(blank=True, choices=[('FLOOR', 'Floor'), ('BENCH', 'Bench'), ('ONBARS', 'On Bars'), ('WALLTOWALL', 'Wall to Wall'), ('ELSE', 'Else')], max_length=10, null=True)),
                ('camID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogs_app.camera')),
                ('dogID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogs_app.dog')),
                ('obsDateTime', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogs_app.observation')),
            ],
            options={
                'ordering': ['-stanceStartTime'],
                'unique_together': {('dogID', 'camID', 'obsDateTime', 'stanceStartTime')},
            },
        ),
    ]
