# Generated by Django 4.2.1 on 2023-06-07 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0009_rename_sessiondurationsinmins_observation_sessiondurationinmins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dateOfArrival',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
