# Generated by Django 4.2.1 on 2023-06-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0012_alter_dog_dogname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('', '-')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='isDangerous',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('', '-')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='isNeutered',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('', '-')], max_length=1, null=True),
        ),
    ]
