# Generated by Django 4.2.1 on 2023-06-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0017_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='dogImageURL',
        ),
        migrations.AddField(
            model_name='dog',
            name='dogImage',
            field=models.ImageField(default='/dog_pictures/default_dog.jpg', upload_to='dog_pictures'),
        ),
    ]
