# Generated by Django 4.2.1 on 2023-07-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0020_alter_dog_dogimage_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/dogs_app/img/default.jpg', upload_to='profile_pictures'),
        ),
    ]
