# Generated by Django 4.2.1 on 2023-07-01 20:39

from django.db import migrations, models
import dogs_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0022_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kennel',
            name='kennelImageURL',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='jsonFileURL',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='rawVideoURL',
        ),
        migrations.AddField(
            model_name='kennel',
            name='kennelImage',
            field=models.ImageField(blank=True, default='kennel_pictures/default_kennel.jpg', null=True, upload_to='kennel_pictures'),
        ),
        migrations.AddField(
            model_name='observation',
            name='jsonFile',
            field=models.FileField(blank=True, null=True, upload_to='json_files', validators=[dogs_app.models.validate_json_file_extension]),
        ),
        migrations.AddField(
            model_name='observation',
            name='rawVideo',
            field=models.FileField(blank=True, null=True, upload_to='raw_videos', validators=[dogs_app.models.validate_video_file_extension]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='isKong',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
    ]
