# Generated by Django 4.2.1 on 2023-07-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0023_remove_kennel_kennelimageurl_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='observation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='observation',
            name='observes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dogs_app.observes'),
        ),
        migrations.AlterField(
            model_name='observes',
            name='camID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observes', to='dogs_app.camera'),
        ),
        migrations.AlterField(
            model_name='observes',
            name='dogID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observers', to='dogs_app.dog'),
        ),
        migrations.AlterUniqueTogether(
            name='observation',
            unique_together={('observes', 'obsDateTime')},
        ),
        migrations.RemoveField(
            model_name='observation',
            name='camID',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='dogID',
        ),
    ]
