# Generated by Django 4.2.1 on 2023-07-02 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0024_alter_observation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dogs_app.observes'),
        ),
    ]
