# Generated by Django 4.2.1 on 2023-07-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0025_alter_observation_observes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dogstance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dogstance',
            name='observation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dogs_app.observation'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dogstance',
            unique_together={('observation', 'stanceStartTime')},
        ),
        migrations.RemoveField(
            model_name='dogstance',
            name='camID',
        ),
        migrations.RemoveField(
            model_name='dogstance',
            name='dogID',
        ),
        migrations.RemoveField(
            model_name='dogstance',
            name='obsDateTime',
        ),
    ]
