# Generated by Django 4.2.1 on 2023-07-02 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0026_alter_dogstance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='observes',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='observes',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observes', to='dogs_app.camera'),
        ),
        migrations.AddField(
            model_name='observes',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observers', to='dogs_app.dog'),
        ),
        migrations.AlterUniqueTogether(
            name='observes',
            unique_together={('dog', 'camera')},
        ),
        migrations.RemoveField(
            model_name='observes',
            name='camID',
        ),
        migrations.RemoveField(
            model_name='observes',
            name='dogID',
        ),
    ]
