# Generated by Django 4.2.1 on 2023-07-02 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0027_alter_observes_unique_together_observes_camera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='ownerSerialNum',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='dogplacement',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='entranceexamination',
            name='dogID',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='dogID',
        ),
        migrations.AddField(
            model_name='dogplacement',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs_app.dog'),
        ),
        migrations.AddField(
            model_name='dogplacement',
            name='kennel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs_app.kennel'),
        ),
        migrations.AddField(
            model_name='entranceexamination',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dogs_app.dog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dogs_app.dog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dogstance',
            name='observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs_app.observation'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs_app.observes'),
        ),
        migrations.AlterUniqueTogether(
            name='dogplacement',
            unique_together={('dog', 'kennel', 'entranceDate')},
        ),
        migrations.RemoveField(
            model_name='dogplacement',
            name='dogID',
        ),
        migrations.RemoveField(
            model_name='dogplacement',
            name='kennelNum',
        ),
    ]
