# Generated by Django 4.2.1 on 2023-09-16 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0029_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='observes',
            name='sessionDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
