# Generated by Django 4.2.1 on 2023-09-17 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0031_alter_observes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='sessionDurationInMins',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
