# Generated by Django 4.2.1 on 2023-10-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0032_alter_observation_sessiondurationinmins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='dogstance',
            name='dogLocation',
            field=models.CharField(blank=True, choices=[('FLOOR', 'On Floor'), ('BENCH', 'On Bench'), ('ONBARS', 'On Bars'), ('WALLTOWALL', 'From Wall to Wall'), ('ELSE', 'And Else')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dogstance',
            name='dogStance',
            field=models.CharField(choices=[('STANDING', 'Standing'), ('SITTING', 'Sitting'), ('WALKING_AROUND', 'Walking Around'), ('SLEEPING_LYING', 'Sleeping/Laying'), ('EATING', 'Eating'), ('DRINKING', 'Drinking'), ('UNDER', 'Under'), ('JUMPING', 'Jumping'), ('PACING', 'Pacing'), ('CIRCLING', 'Circling'), ('ALERT', 'Alert'), ('ELSE', 'Else')], max_length=15),
        ),
    ]
