# Generated by Django 4.2.1 on 2023-12-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0039_alter_owner_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
