# Generated by Django 4.2.1 on 2024-01-07 07:19

from django.db import migrations, models
import dogs_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0040_alter_owner_phonenum'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='owner',
            name='phoneNum_check',
        ),
        migrations.RemoveConstraint(
            model_name='owner',
            name='cellphoneNum_check',
        ),
        migrations.AlterField(
            model_name='owner',
            name='cellphoneNum',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[dogs_app.models.validate_cellphoneNum]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[dogs_app.models.validate_phoneNum]),
        ),
    ]
