# Generated by Django 4.2.1 on 2024-01-07 07:38

from django.db import migrations, models
import dogs_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0041_remove_owner_phonenum_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='ownerID',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[dogs_app.models.validate_ownerID]),
        ),
    ]
