# Generated by Django 4.2.1 on 2024-01-10 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dogs_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0042_alter_owner_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camID',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Camera ID'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs_app.dog', verbose_name='Dog'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='dogPulse',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pulse'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='dogTemperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='dogWeight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='examinationDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Examination Date'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='examinationID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Examination ID'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='examinedBy',
            field=models.CharField(max_length=50, verbose_name='Examined By'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='results',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Results'),
        ),
        migrations.AlterField(
            model_name='kennel',
            name='kennelImage',
            field=models.ImageField(blank=True, default='kennel_pictures/default_kennel.jpg', null=True, upload_to='kennel_pictures', verbose_name='Kennel Image'),
        ),
        migrations.AlterField(
            model_name='kennel',
            name='kennelNum',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Kennel Number'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='cellphoneNum',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[dogs_app.models.validate_cellphoneNum], verbose_name='Cellphone Number'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerAddress',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerID',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[dogs_app.models.validate_ownerID], verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerSerialNum',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Owner Serial Number'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[dogs_app.models.validate_phoneNum], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs_app.dog', verbose_name='Dog'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatedBy',
            field=models.CharField(max_length=50, verbose_name='Treated By'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatmentDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Treatment'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatmentID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Treatment ID'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatmentName',
            field=models.CharField(max_length=50, verbose_name='Treatment Name'),
        ),
    ]
