# Generated by Django 4.2.1 on 2024-01-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0043_alter_camera_camid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entranceexamination',
            name='dogTemperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperature'),
        ),
    ]
