# Generated by Django 4.2.1 on 2024-01-14 02:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dogs_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0044_alter_entranceexamination_dogtemperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogplacement',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs_app.dog', verbose_name='Dog'),
        ),
        migrations.AlterField(
            model_name='dogplacement',
            name='entranceDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Entrance Date'),
        ),
        migrations.AlterField(
            model_name='dogplacement',
            name='expirationDate',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='dogplacement',
            name='kennel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs_app.kennel', verbose_name='Kennel'),
        ),
        migrations.AlterField(
            model_name='dogplacement',
            name='placementReason',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Placement Reason'),
        ),
        migrations.AlterField(
            model_name='dogstance',
            name='dogLocation',
            field=models.CharField(blank=True, choices=[('FLOOR', 'On Floor'), ('BENCH', 'On Bench'), ('ONBARS', 'On Bars'), ('WALLTOWALL', 'From Wall to Wall'), ('ELSE', 'Else')], max_length=10, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='dogstance',
            name='dogStance',
            field=models.CharField(choices=[('STANDING', 'Standing'), ('SITTING', 'Sitting'), ('WALKING_AROUND', 'Walking Around'), ('SLEEPING_LYING', 'Sleeping/Laying'), ('EATING', 'Eating'), ('DRINKING', 'Drinking'), ('UNDER', 'Under'), ('JUMPING', 'Jumping'), ('PACING', 'Pacing'), ('CIRCLING', 'Circling'), ('ALERT', 'Alert'), ('ELSE', 'Else')], max_length=15, verbose_name='Stance'),
        ),
        migrations.AlterField(
            model_name='dogstance',
            name='observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs_app.observation', verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='dogstance',
            name='stanceStartTime',
            field=models.TimeField(verbose_name='Stance Start Time'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='isKong',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True, verbose_name='Kong'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='jsonFile',
            field=models.FileField(blank=True, null=True, upload_to='json_files', validators=[dogs_app.models.validate_json_file_extension], verbose_name='JSON File'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obsDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Starting Date and Time'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs_app.observes', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='rawVideo',
            field=models.FileField(blank=True, null=True, upload_to='raw_videos', validators=[dogs_app.models.validate_video_file_extension], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='sessionDurationInMins',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Session Duration (mins)'),
        ),
        migrations.AlterField(
            model_name='observes',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observes', to='dogs_app.camera', verbose_name='Camera'),
        ),
        migrations.AlterField(
            model_name='observes',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='observes',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observers', to='dogs_app.dog', verbose_name='Dog'),
        ),
        migrations.AlterField(
            model_name='observes',
            name='sessionDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Session Start Date'),
        ),
    ]
