# Generated by Django 4.2.1 on 2024-02-07 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0045_alter_dogplacement_dog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(max_length=20, unique=True, verbose_name='Branch Name')),
            ],
        ),
        migrations.AlterField(
            model_name='observation',
            name='obsDateTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Starting Date and Time'),
        ),
    ]
