# Generated by Django 4.2.1 on 2024-02-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0047_alter_branch_options_alter_news_options_news_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dogs_app.branch', verbose_name='Branch'),
            preserve_default=False,
        ),
    ]
