# Generated by Django 4.2.1 on 2024-02-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0048_owner_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennel',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dogs_app.branch', verbose_name='Branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('', '-')], max_length=1, null=True),
        ),
    ]
