# Generated by Django 4.2.1 on 2024-02-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0049_kennel_branch_alter_dog_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kennel',
            options={'ordering': (['kennelNum'],)},
        ),
        migrations.AlterUniqueTogether(
            name='kennel',
            unique_together={('kennelNum', 'branch')},
        ),
    ]
