# Generated by Django 4.2.1 on 2024-02-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0050_alter_kennel_options_alter_kennel_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kennel',
            options={'ordering': (['kennelNum', 'branch'],)},
        ),
    ]
