# Generated by Django 4.2.1 on 2024-02-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0051_alter_kennel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kennel',
            options={'ordering': ['kennelNum', 'branch']},
        ),
    ]
