# Generated by Django 4.2.1 on 2024-02-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0052_alter_kennel_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kennel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='kennel',
            name='branch',
        ),
        migrations.DeleteModel(
            name='DogPlacement',
        ),
        migrations.DeleteModel(
            name='Kennel',
        ),
    ]
