# Generated by Django 4.2.1 on 2024-02-12 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0054_kennel_dogplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dogs_app.branch', verbose_name='Branch'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('camID', 'branch')},
        ),
    ]
