# Generated by Django 4.2.1 on 2024-02-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0055_camera_branch_alter_camera_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dogstance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dogstance',
            name='observation',
        ),
        migrations.AlterUniqueTogether(
            name='observation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='observation',
            name='observes',
        ),
        migrations.AlterUniqueTogether(
            name='observes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='observes',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='observes',
            name='dog',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='DogStance',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='Observes',
        ),
    ]
