# Generated by Django 4.2.1 on 2024-02-14 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dogs_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0056_alter_dogstance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camID', models.PositiveSmallIntegerField(verbose_name='Camera ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs_app.branch', verbose_name='Branch')),
            ],
            options={
                'ordering': ['camID'],
                'unique_together': {('camID', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='Observes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionDate', models.DateField(default=django.utils.timezone.now, verbose_name='Session Start Date')),
                ('comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comments')),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observes', to='dogs_app.camera', verbose_name='Camera')),
                ('dog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observers', to='dogs_app.dog', verbose_name='Dog')),
            ],
            options={
                'verbose_name_plural': 'Observes',
                'unique_together': {('dog', 'camera', 'sessionDate')},
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsDateTime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Starting Date and Time')),
                ('sessionDurationInMins', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Session Duration (mins)')),
                ('isKong', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True, verbose_name='Kong')),
                ('jsonFile', models.FileField(blank=True, null=True, upload_to='json_files', validators=[dogs_app.models.validate_json_file_extension], verbose_name='JSON File')),
                ('rawVideo', models.FileField(blank=True, null=True, upload_to='raw_videos', validators=[dogs_app.models.validate_video_file_extension], verbose_name='Video')),
                ('observes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs_app.observes', verbose_name='Session')),
            ],
            options={
                'ordering': ['-obsDateTime'],
                'unique_together': {('observes', 'obsDateTime')},
            },
        ),
        migrations.CreateModel(
            name='DogStance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stanceStartTime', models.TimeField(verbose_name='Stance Start Time')),
                ('dogStance', models.CharField(choices=[('STANDING', 'Standing'), ('SITTING', 'Sitting'), ('WALKING_AROUND', 'Walking Around'), ('SLEEPING_LYING', 'Sleeping/Laying'), ('EATING', 'Eating'), ('DRINKING', 'Drinking'), ('UNDER', 'Under'), ('JUMPING', 'Jumping'), ('PACING', 'Pacing'), ('CIRCLING', 'Circling'), ('ALERT', 'Alert'), ('ELSE', 'Else')], max_length=15, verbose_name='Stance')),
                ('dogLocation', models.CharField(blank=True, choices=[('FLOOR', 'On Floor'), ('BENCH', 'On Bench'), ('ONBARS', 'On Bars'), ('WALLTOWALL', 'From Wall to Wall'), ('ELSE', 'Else')], max_length=10, null=True, verbose_name='Location')),
                ('observation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs_app.observation', verbose_name='Observation')),
            ],
            options={
                'ordering': ['-stanceStartTime'],
                'unique_together': {('observation', 'stanceStartTime')},
            },
        ),
    ]
