# Generated by Django 4.2.1 on 2024-02-20 18:24

import django.core.validators
from django.db import migrations, models
import dogs_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0059_alter_dog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dateOfArrival',
            field=models.DateField(blank=True, default=dogs_app.models.current_timezone_aware_date, null=True),
        ),
        migrations.AlterField(
            model_name='dogplacement',
            name='entranceDate',
            field=models.DateField(default=dogs_app.models.current_timezone_aware_date, verbose_name='Entrance Date'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='dogPulse',
            field=models.PositiveSmallIntegerField(blank=True, help_text='In BPM', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Pulse'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='dogTemperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='In Celsius', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='dogWeight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='In Kilograms', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='examinationDate',
            field=models.DateField(default=dogs_app.models.current_timezone_aware_date, verbose_name='Examination Date'),
        ),
        migrations.AlterField(
            model_name='entranceexamination',
            name='results',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Results'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obsDateTime',
            field=models.DateTimeField(db_index=True, default=dogs_app.models.current_timezone_aware_datetime, verbose_name='Starting Date and Time'),
        ),
        migrations.AlterField(
            model_name='observes',
            name='sessionDate',
            field=models.DateField(default=dogs_app.models.get_current_date_jerusalem, verbose_name='Session Start Date'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerAddress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatmentDate',
            field=models.DateField(blank=True, default=dogs_app.models.current_timezone_aware_date, null=True, verbose_name='Date of Treatment'),
        ),
    ]
