# Generated by Django 4.2.1 on 2024-02-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0060_alter_dog_dateofarrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogstance',
            name='observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs_app.observation', verbose_name='Observation'),
        ),
    ]
