# Generated by Django 4.2.1 on 2024-02-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0061_alter_dogstance_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogplacement',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs_app.dog', verbose_name='Dog'),
        ),
        migrations.AlterField(
            model_name='dogplacement',
            name='kennel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs_app.kennel', verbose_name='Kennel'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs_app.observes', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='observes',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observes', to='dogs_app.camera', verbose_name='Camera'),
        ),
        migrations.AlterField(
            model_name='observes',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observers', to='dogs_app.dog', verbose_name='Dog'),
        ),
    ]
