# Generated by Django 4.2.1 on 2024-03-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0062_alter_dogplacement_dog_alter_dogplacement_kennel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='adoptionDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Adoption Date'),
        ),
    ]
