# Generated by Django 4.2.1 on 2024-03-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0063_dog_adoptiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='isDog',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True, verbose_name='With Dog'),
        ),
        migrations.AddField(
            model_name='observation',
            name='isHuman',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True, verbose_name='With Human'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='isKong',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True, verbose_name='With Kong'),
        ),
    ]
