# Generated by Django 4.2.1 on 2024-03-05 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0064_observation_isdog_observation_ishuman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='isDog',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default=None, max_length=1, null=True, verbose_name='With Dog'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='isHuman',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default=None, max_length=1, null=True, verbose_name='With Human'),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs_app.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name_plural': 'Poll',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs_app.poll')),
            ],
        ),
    ]
