# Generated by Django 4.2.1 on 2024-03-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0066_alter_poll_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogstance',
            name='dogLocation',
            field=models.CharField(blank=True, choices=[('FLOOR', 'On Floor'), ('BENCH', 'On Bench'), ('ONBARS', 'On Bars'), ('ONBED', 'On Bed'), ('WALLTOWALL', 'From Wall to Wall'), ('ELSE', 'Else')], max_length=10, null=True, verbose_name='Location'),
        ),
    ]
