# Generated by Django 4.2.1 on 2024-03-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0067_alter_dogstance_doglocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='kongDateAdded',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Last Date Given a Kong'),
        ),
    ]
