# Generated by Django 4.2.1 on 2024-03-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0068_alter_dog_kongdateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branchAddress',
            field=models.CharField(default='Default', max_length=100, verbose_name='Branch Address'),
            preserve_default=False,
        ),
    ]
