# Generated by Django 4.2.1 on 2024-03-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0069_branch_branchaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branchCity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Branch City'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branchAddress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch Address'),
        ),
    ]
