# Generated by Django 4.2.1 on 2024-03-13 00:10

from django.db import migrations, models
import dogs_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0071_observation_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original File Name'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='csvFile',
            field=models.FileField(blank=True, null=True, upload_to='csv_files', validators=[dogs_app.models.validate_csv_file_extension], verbose_name='Sensory Data File'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='rawVideo',
            field=models.FileField(blank=True, null=True, upload_to='raw_videos', validators=[dogs_app.models.validate_video_file_extension], verbose_name='Observation Video File'),
        ),
    ]
