# Generated by Django 4.2.1 on 2024-03-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0072_observation_original_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='original_file_name',
            new_name='original_csv_file_name',
        ),
    ]
