# Generated by Django 4.2.1 on 2024-03-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0073_rename_original_file_name_observation_original_csv_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='original_video_file_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Original Video File Name'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='original_csv_file_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Original File Name'),
        ),
    ]
