# Generated by Django 4.2.1 on 2024-06-05 12:20

from django.db import migrations, models
import dogs_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0074_observation_original_video_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='csvFile',
            field=models.FileField(blank=True, null=True, upload_to='csv_files', validators=[dogs_app.models.validate_csv_file_extension], verbose_name='Sensory Data'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='isKong',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True, verbose_name='With Toy'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='rawVideo',
            field=models.FileField(blank=True, null=True, upload_to='raw_videos', validators=[dogs_app.models.validate_video_file_extension], verbose_name='Video'),
        ),
    ]
