# Generated by Django 4.2.1 on 2024-06-20 14:48

from django.db import migrations, models
import dogs_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0075_alter_observation_csvfile_alter_observation_iskong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='colorGroup',
            field=models.CharField(blank=True, choices=[('P', 'Purple'), ('O', 'Orange'), ('G', 'Green'), ('PO', 'Purple/Orange'), ('', '-')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='dogImage2',
            field=models.ImageField(blank=True, default='dog_pictures/default_dog.jpg', null=True, upload_to='dog_pictures'),
        ),
        migrations.AddField(
            model_name='dog',
            name='dogImage3',
            field=models.ImageField(blank=True, default='dog_pictures/default_dog.jpg', null=True, upload_to='dog_pictures'),
        ),
        migrations.AddField(
            model_name='dog',
            name='dogImage4',
            field=models.ImageField(blank=True, default='dog_pictures/default_dog.jpg', null=True, upload_to='dog_pictures'),
        ),
        migrations.AddField(
            model_name='dog',
            name='dogVideo',
            field=models.FileField(blank=True, null=True, upload_to='dog_videos', validators=[dogs_app.models.validate_video_file_extension], verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='dog',
            name='entryReason',
            field=models.CharField(blank=True, choices=[('STRAY', 'Stray'), ('BITE', 'Bite'), ('RETURN', 'Returning'), ('ELSE', 'Else'), ('', '-')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='motivationGroup',
            field=models.CharField(blank=True, choices=[('EXTERNALLY', 'Externally'), ('INTERNALLY', 'Internally'), ('SOCIALLY', 'Socially'), ('', '-')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='releaseDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='releaseDetails',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='releaseReason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
