"""
Django base settings for dogshelter_site project.

Uses common settings for both Production and Local settings
which are run with local.py and production.py accordingly

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default=get_random_secret_key())

# Application definition
INSTALLED_APPS = [
    'dogs_app.apps.DogsAppConfig',
    'portal_app.apps.PortalAppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',        # Was used to reset the database
    'widget_tweaks',            # Tweaks for widgets
    'storages',                 # For the AWS S3 cloud for pictures/videos uploads
    'crispy_forms',             # Better looking forms
    'crispy_bootstrap5',
    'django_filters',           # For advanced filtering of data
    'datetimewidget',           # For selecting DateTime in forms
    'django_tables2',           # For better looking tables
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'dogs_app.set_default_branch_middleware.set_default_branch_middleware',  # Set default branch for the app
]

ROOT_URLCONF = 'dogshelter_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dogs_app.breadcrumb_context_processor.breadcrumb_processor',  # For Breadcrumbs above pages
            ],
        },
    },
]

WSGI_APPLICATION = 'dogshelter_site.wsgi.application'

# Database configuration moved to local.py and production.py

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Jerusalem'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'dogs_app', 'static'),
    os.path.join(BASE_DIR, 'portal_app', 'static'),
]

# List of video files allowed to upload to the system
ALLOWED_VIDEO_FILE_EXTENSIONS = ['.mp4', '.avi', '.mov', '.flv', '.wmv', '.mkv', '.webm', '.3gp', '.ogg', '.ogv',
                                 '.mpeg', '.mpg', '.m4v']

# For better looking HTML
CRISPY_TEMPLATE_PACK = 'bootstrap5'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

# Table configuration
DJANGO_TABLES2_TABLE_ATTRS = {
   'class': 'table table-hover table-bordered table-striped border-dark',
   'thead': {
       'class': 'table-light border-dark',
   },
}

DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap5.html"
